language: node_js

node_js: "4"

os:
- linux
- osx
matrix:
  fast_finish: true

branches:
  only:
    - master
    - beta

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
    - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
            export CXX=g++-4.8;1
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
            sleep 8;
        fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm run coverage

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
