language: node_js

node_js: "4"

os:
- linux
- osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
    - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
            export CXX=g++-4.8;
            sleep 8;
        fi
    - curl https://install.meteor.com | /bin/sh
    - export PATH="$HOME/.meteor:$PATH"

script:
    - npm test
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
            npm run prepare-integration-tests;
            npm run test-integration;
        fi

after_success:
  - npm run coverage
  - npm run report-coverage

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
