language: node_js

node_js:
 - 4
 - 6

os:
 - linux
 - osx

env:
  matrix:
    - TEST=normal
    - TEST=integration

matrix:
  exclude:
    - env: TEST=integration
      os: osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
    - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
            export CXX=g++-4.8;
            sleep 8;
            if [[ "$TEST" == "integration" ]]; then
                curl https://install.meteor.com/?release=1.4.2 | /bin/sh;
                export PATH="$HOME/.meteor:$PATH";
            fi
      fi

script:
    - if [[ "$TEST" == "normal" ]]; then
        npm test;
      fi
    - if [[ "$TEST" == "integration" ]]; then
            npm run prepare-integration-tests;
            npm run test-integration;
      fi

after_success:
  - if [[ "$TEST" == "normal" ]]; then
      npm run coverage;
      npm run report-coverage;
    fi

cache:
  directories:
    - node_modules
    - $HOME/.electron
    - $HOME/.npm
    - $HOME/.yarn-cache

notifications:
  email:
    on_success: never
    on_failure: change
