language: node_js

node_js: "4"

os:
- linux
- osx
matrix:
  fast_finish: true

branches:
  only:
    - master
    - beta


before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        export DISPLAY=:99.0;
        sh -e /etc/init.d/xvfb start;
        sleep 8;
    fi

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
