build: off

os: unstable

branches:
  only:
    - master
    - beta

skip_tags: true

environment:
  nodejs_version: "4.4.0"

cache:
  - node_modules -> package.json
  - '%HOMEPATH%\AppData\Local\.meteor'

install:
 # Download Meteor
  - ps: Install-Product node $env:nodejs_version
  - npm install npm
  - ps: Start-FileDownload 'https://s3.amazonaws.com/meteor-windows/InstallMeteor.exe'
  # Install meteor
  - .\installMeteor.exe /passive
  # Restart
  - ps: Start-Sleep -s 5
  - ps: Restart-Computer -Force

# Post-install test scripts.
test_script:
  - node --version
  - npm --version
  - meteor --version
  - npm test
  - npm run prepare-integration-test
  - npm run test-integration

