build: off

os: unstable

skip_tags: true

environment:
  matrix:
    - nodejs_version: "4.4.0"
    - nodejs_version: "6.9.1"

platform:
  - x86
  - x64

cache:
  - node_modules -> package.json

install:
 # Download Meteor
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@next
  - npm install
  - ps: Start-FileDownload 'https://s3.amazonaws.com/meteor-windows/InstallMeteor.exe'
  # Install meteor
  - .\installMeteor.exe /passive
  - cmd: cd C:\Users\appveyor\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid && rmdir /S /Q node_modules && npm install
  # Restart
  - ps: Start-Sleep -s 5
  - ps: Restart-Computer -Force

# Post-install test scripts.
test_script:
  - node --version
  - npm --version
  - meteor --version
  - npm test
  - npm run prepare-integration-tests
  - npm run test-integration

