build: off

os: unstable

skip_tags: true

environment:
  matrix:
    - nodejs_version: "4.4.0"
      TEST: "normal"
    - nodejs_version: "6.9.1"
      TEST: "normal"
    - nodejs_version: "4.4.0"
      TEST: "integration"
    - nodejs_version: "6.9.1"
      TEST: "integration"

platform:
  - x86
  - x64

cache:
  - node_modules -> package.json

install:
 # Download Meteor
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - ps: |
        if ($env.TEST -eq "integration") {
            Start-FileDownload 'https://s3.amazonaws.com/meteor-windows/InstallMeteor.exe'
            .\installMeteor.exe /passive
            cd C:\Users\appveyor\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid
            Remove-Item node_modules -Recurse -Force
            npm install
            Start-Sleep -s 5
            Restart-Computer -Force
        }

# Post-install test scripts.
test_script:
  - node --version
  - npm --version
  - ps: |
        if ($env.TEST -eq "normal") {
            npm test
        }
        else {
            meteor --version
            npm run prepare-integration-tests
            npm run test-integration
        }

